// 武将データベース
// 基礎能力値はLv1時点。レベル・覚醒・ポイント割り振りでUI上で調整
// aptitude: 兵科適性 { cavalry, shield, archer, spear, siege }

export const GENERALS = [
  // ===== 魏 =====
  { id: 'wei001', name: '曹操',   rarity: 5, faction: 'wei', cost: 4, type: 'balance',
    baseStats: { atk: 92, def: 85, strat: 95, spd: 88, pol: 98, charm: 96 },
    aptitude: { cavalry: 'S', shield: 'A', archer: 'A', spear: 'B', siege: 'B' },
    uniqueSkill: 'sk_souso_unique', skills: [] },
  { id: 'wei002', name: '夏侯惇', rarity: 5, faction: 'wei', cost: 3.5, type: 'attack',
    baseStats: { atk: 96, def: 82, strat: 45, spd: 78, pol: 32, charm: 70 },
    aptitude: { cavalry: 'A', shield: 'S', archer: 'C', spear: 'A', siege: 'B' },
    uniqueSkill: 'sk_kakoton_unique', skills: [] },
  { id: 'wei003', name: '司馬懿', rarity: 5, faction: 'wei', cost: 4, type: 'strategy',
    baseStats: { atk: 40, def: 78, strat: 98, spd: 85, pol: 96, charm: 80 },
    aptitude: { cavalry: 'B', shield: 'A', archer: 'A', spear: 'B', siege: 'S' },
    uniqueSkill: 'sk_shibai_unique', skills: [] },
  { id: 'wei004', name: '張遼',   rarity: 5, faction: 'wei', cost: 3.5, type: 'attack',
    baseStats: { atk: 95, def: 80, strat: 55, spd: 92, pol: 40, charm: 75 },
    aptitude: { cavalry: 'S', shield: 'B', archer: 'B', spear: 'A', siege: 'C' },
    uniqueSkill: 'sk_choryo_unique', skills: [] },
  { id: 'wei005', name: '典韋',   rarity: 4, faction: 'wei', cost: 3, type: 'defense',
    baseStats: { atk: 90, def: 92, strat: 20, spd: 65, pol: 15, charm: 55 },
    aptitude: { cavalry: 'B', shield: 'S', archer: 'C', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'wei006', name: '荀彧',   rarity: 4, faction: 'wei', cost: 2.5, type: 'support',
    baseStats: { atk: 25, def: 55, strat: 90, spd: 72, pol: 95, charm: 88 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'A', spear: 'C', siege: 'A' },
    uniqueSkill: null, skills: [] },
  { id: 'wei007', name: '許褚',   rarity: 4, faction: 'wei', cost: 3, type: 'attack',
    baseStats: { atk: 93, def: 88, strat: 18, spd: 60, pol: 10, charm: 45 },
    aptitude: { cavalry: 'B', shield: 'A', archer: 'C', spear: 'S', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'wei008', name: '夏侯淵', rarity: 4, faction: 'wei', cost: 3, type: 'speed',
    baseStats: { atk: 88, def: 68, strat: 42, spd: 95, pol: 30, charm: 60 },
    aptitude: { cavalry: 'S', shield: 'C', archer: 'A', spear: 'B', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'wei009', name: '曹仁',   rarity: 4, faction: 'wei', cost: 3, type: 'defense',
    baseStats: { atk: 78, def: 95, strat: 48, spd: 62, pol: 55, charm: 65 },
    aptitude: { cavalry: 'A', shield: 'S', archer: 'B', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'wei010', name: '李典',   rarity: 3, faction: 'wei', cost: 2, type: 'balance',
    baseStats: { atk: 72, def: 68, strat: 60, spd: 70, pol: 55, charm: 58 },
    aptitude: { cavalry: 'A', shield: 'B', archer: 'A', spear: 'B', siege: 'C' },
    uniqueSkill: null, skills: [] },

  // ===== 呉 =====
  { id: 'wu001', name: '孫策',   rarity: 5, faction: 'wu', cost: 4, type: 'attack',
    baseStats: { atk: 97, def: 72, strat: 60, spd: 90, pol: 55, charm: 92 },
    aptitude: { cavalry: 'S', shield: 'B', archer: 'A', spear: 'A', siege: 'C' },
    uniqueSkill: 'sk_sonsaku_unique', skills: [] },
  { id: 'wu002', name: '孫権',   rarity: 5, faction: 'wu', cost: 3.5, type: 'balance',
    baseStats: { atk: 72, def: 80, strat: 82, spd: 75, pol: 92, charm: 95 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'A', spear: 'B', siege: 'A' },
    uniqueSkill: 'sk_sonken_unique', skills: [] },
  { id: 'wu003', name: '周瑜',   rarity: 5, faction: 'wu', cost: 4, type: 'strategy',
    baseStats: { atk: 50, def: 70, strat: 97, spd: 82, pol: 88, charm: 94 },
    aptitude: { cavalry: 'B', shield: 'A', archer: 'S', spear: 'C', siege: 'A' },
    uniqueSkill: 'sk_shuyu_unique', skills: [] },
  { id: 'wu004', name: '甘寧',   rarity: 4, faction: 'wu', cost: 3, type: 'attack',
    baseStats: { atk: 94, def: 70, strat: 35, spd: 88, pol: 20, charm: 60 },
    aptitude: { cavalry: 'A', shield: 'B', archer: 'S', spear: 'A', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'wu005', name: '陸遜',   rarity: 5, faction: 'wu', cost: 3.5, type: 'strategy',
    baseStats: { atk: 42, def: 72, strat: 96, spd: 80, pol: 90, charm: 85 },
    aptitude: { cavalry: 'B', shield: 'A', archer: 'A', spear: 'B', siege: 'S' },
    uniqueSkill: 'sk_rikuson_unique', skills: [] },
  { id: 'wu006', name: '太史慈', rarity: 4, faction: 'wu', cost: 3, type: 'attack',
    baseStats: { atk: 92, def: 72, strat: 38, spd: 85, pol: 28, charm: 68 },
    aptitude: { cavalry: 'A', shield: 'C', archer: 'S', spear: 'B', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'wu007', name: '呂蒙',   rarity: 4, faction: 'wu', cost: 3, type: 'balance',
    baseStats: { atk: 78, def: 75, strat: 82, spd: 72, pol: 70, charm: 72 },
    aptitude: { cavalry: 'B', shield: 'A', archer: 'A', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'wu008', name: '小喬',   rarity: 4, faction: 'wu', cost: 2.5, type: 'support',
    baseStats: { atk: 20, def: 48, strat: 85, spd: 78, pol: 80, charm: 98 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'A', spear: 'C', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'wu009', name: '黄蓋',   rarity: 3, faction: 'wu', cost: 2, type: 'defense',
    baseStats: { atk: 78, def: 82, strat: 42, spd: 55, pol: 38, charm: 55 },
    aptitude: { cavalry: 'C', shield: 'A', archer: 'B', spear: 'A', siege: 'A' },
    uniqueSkill: null, skills: [] },

  // ===== 蜀 =====
  { id: 'shu001', name: '劉備',   rarity: 5, faction: 'shu', cost: 3.5, type: 'support',
    baseStats: { atk: 70, def: 72, strat: 75, spd: 70, pol: 85, charm: 99 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'B', spear: 'A', siege: 'B' },
    uniqueSkill: 'sk_ryubi_unique', skills: [] },
  { id: 'shu002', name: '関羽',   rarity: 5, faction: 'shu', cost: 4, type: 'attack',
    baseStats: { atk: 98, def: 85, strat: 62, spd: 78, pol: 55, charm: 90 },
    aptitude: { cavalry: 'S', shield: 'A', archer: 'C', spear: 'A', siege: 'B' },
    uniqueSkill: 'sk_kannu_unique', skills: [] },
  { id: 'shu003', name: '張飛',   rarity: 5, faction: 'shu', cost: 3.5, type: 'attack',
    baseStats: { atk: 99, def: 78, strat: 30, spd: 82, pol: 18, charm: 55 },
    aptitude: { cavalry: 'A', shield: 'B', archer: 'C', spear: 'S', siege: 'B' },
    uniqueSkill: 'sk_chohi_unique', skills: [] },
  { id: 'shu004', name: '諸葛亮', rarity: 5, faction: 'shu', cost: 4, type: 'strategy',
    baseStats: { atk: 35, def: 75, strat: 100, spd: 80, pol: 100, charm: 92 },
    aptitude: { cavalry: 'C', shield: 'A', archer: 'A', spear: 'B', siege: 'S' },
    uniqueSkill: 'sk_shokatsu_unique', skills: [] },
  { id: 'shu005', name: '趙雲',   rarity: 5, faction: 'shu', cost: 3.5, type: 'balance',
    baseStats: { atk: 95, def: 82, strat: 68, spd: 90, pol: 55, charm: 88 },
    aptitude: { cavalry: 'S', shield: 'A', archer: 'B', spear: 'A', siege: 'C' },
    uniqueSkill: 'sk_choun_unique', skills: [] },
  { id: 'shu006', name: '馬超',   rarity: 4, faction: 'shu', cost: 3.5, type: 'attack',
    baseStats: { atk: 96, def: 72, strat: 40, spd: 92, pol: 25, charm: 72 },
    aptitude: { cavalry: 'S', shield: 'C', archer: 'B', spear: 'A', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'shu007', name: '黄忠',   rarity: 4, faction: 'shu', cost: 3, type: 'attack',
    baseStats: { atk: 92, def: 75, strat: 45, spd: 68, pol: 30, charm: 60 },
    aptitude: { cavalry: 'B', shield: 'B', archer: 'S', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'shu008', name: '龐統',   rarity: 4, faction: 'shu', cost: 3, type: 'strategy',
    baseStats: { atk: 30, def: 60, strat: 95, spd: 75, pol: 92, charm: 65 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'A', spear: 'C', siege: 'A' },
    uniqueSkill: null, skills: [] },
  { id: 'shu009', name: '魏延',   rarity: 4, faction: 'shu', cost: 3, type: 'attack',
    baseStats: { atk: 90, def: 78, strat: 55, spd: 80, pol: 35, charm: 40 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'C', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'shu010', name: '姜維',   rarity: 4, faction: 'shu', cost: 3, type: 'balance',
    baseStats: { atk: 88, def: 78, strat: 85, spd: 82, pol: 72, charm: 70 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'B', spear: 'A', siege: 'B' },
    uniqueSkill: null, skills: [] },

  // ===== 他 =====
  { id: 'oth001', name: '呂布',   rarity: 5, faction: 'other', cost: 4.5, type: 'attack',
    baseStats: { atk: 100, def: 80, strat: 28, spd: 95, pol: 12, charm: 30 },
    aptitude: { cavalry: 'S', shield: 'B', archer: 'B', spear: 'A', siege: 'C' },
    uniqueSkill: 'sk_ryofu_unique', skills: [] },
  { id: 'oth002', name: '貂蝉',   rarity: 5, faction: 'other', cost: 3, type: 'support',
    baseStats: { atk: 22, def: 45, strat: 78, spd: 75, pol: 62, charm: 100 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'A', spear: 'C', siege: 'B' },
    uniqueSkill: 'sk_chosen_unique', skills: [] },
  { id: 'oth003', name: '董卓',   rarity: 4, faction: 'other', cost: 3.5, type: 'balance',
    baseStats: { atk: 82, def: 78, strat: 55, spd: 40, pol: 60, charm: 20 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'B', spear: 'B', siege: 'A' },
    uniqueSkill: null, skills: [] },
  { id: 'oth004', name: '張角',   rarity: 4, faction: 'other', cost: 3, type: 'strategy',
    baseStats: { atk: 30, def: 55, strat: 92, spd: 68, pol: 72, charm: 85 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'B', spear: 'C', siege: 'A' },
    uniqueSkill: null, skills: [] },
  { id: 'oth005', name: '袁紹',   rarity: 4, faction: 'other', cost: 3, type: 'support',
    baseStats: { atk: 55, def: 65, strat: 52, spd: 50, pol: 78, charm: 82 },
    aptitude: { cavalry: 'A', shield: 'A', archer: 'A', spear: 'B', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'oth006', name: '華佗',   rarity: 4, faction: 'other', cost: 2.5, type: 'support',
    baseStats: { atk: 15, def: 40, strat: 88, spd: 65, pol: 85, charm: 90 },
    aptitude: { cavalry: 'C', shield: 'C', archer: 'B', spear: 'C', siege: 'B' },
    uniqueSkill: null, skills: [] },
  { id: 'oth007', name: '公孫瓚', rarity: 3, faction: 'other', cost: 2.5, type: 'attack',
    baseStats: { atk: 82, def: 68, strat: 35, spd: 80, pol: 42, charm: 55 },
    aptitude: { cavalry: 'S', shield: 'C', archer: 'B', spear: 'B', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'oth008', name: '張繡',   rarity: 3, faction: 'other', cost: 2, type: 'attack',
    baseStats: { atk: 78, def: 62, strat: 32, spd: 75, pol: 28, charm: 42 },
    aptitude: { cavalry: 'A', shield: 'B', archer: 'C', spear: 'A', siege: 'C' },
    uniqueSkill: null, skills: [] },
  { id: 'oth009', name: '陳宮',   rarity: 3, faction: 'other', cost: 2, type: 'strategy',
    baseStats: { atk: 25, def: 48, strat: 82, spd: 68, pol: 78, charm: 55 },
    aptitude: { cavalry: 'C', shield: 'B', archer: 'A', spear: 'C', siege: 'A' },
    uniqueSkill: null, skills: [] },
];

// 武将名でクイック検索用のマップ
export const GENERALS_BY_ID = Object.fromEntries(GENERALS.map(g => [g.id, g]));
